# Generated by Django 4.2.4 on 2023-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_id_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='chat id'),
        ),
    ]
