# Generated by Django 4.2.4 on 2023-09-25 18:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='location')),
                ('time', models.TimeField(default=datetime.datetime(2023, 9, 25, 18, 42, 42, 866317, tzinfo=datetime.timezone.utc), verbose_name='time')),
                ('action', models.CharField(max_length=1000, verbose_name='action')),
                ('is_pleasant', models.BooleanField(verbose_name='is pleasant')),
                ('periodicity_in_hours', models.IntegerField(verbose_name='periodicity in hours')),
                ('reward', models.CharField(max_length=300, verbose_name='reward')),
                ('time_to_complete', models.TimeField(default=datetime.time(0, 5), verbose_name='time_to_complete')),
                ('is_public', models.BooleanField(verbose_name='is_public')),
                ('associated_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useful_habits.usefulhabit', verbose_name='associated habit')),
            ],
            options={
                'verbose_name': 'useful_habit',
                'verbose_name_plural': 'useful_habits',
                'ordering': ('owner',),
            },
        ),
    ]
