# Generated by Django 4.2.4 on 2023-09-28 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 28, 10, 52, 21, 344795, tzinfo=datetime.timezone.utc), verbose_name='time'),
        ),
    ]
