# Generated by Django 4.2.4 on 2023-09-28 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0003_alter_usefulhabit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='associated_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useful_habits.usefulhabit', verbose_name='associated habit'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 28, 12, 52, 39, 2917, tzinfo=datetime.timezone.utc), verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='time_to_complete',
            field=models.TimeField(default=datetime.time(0, 2), verbose_name='time_to_complete'),
        ),
    ]
