# Generated by Django 4.2.4 on 2023-09-28 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0004_alter_usefulhabit_associated_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='reward',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='reward'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 28, 13, 2, 29, 448761, tzinfo=datetime.timezone.utc), verbose_name='time'),
        ),
    ]
