# Generated by Django 4.2.4 on 2023-10-04 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0010_alter_usefulhabit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 4, 17, 32, 38, 274724), verbose_name='time'),
        ),
    ]
